Emacs Config

* Package Configurations

   First, I need to setup Package and Melpa.

   #+begin_src emacs-lisp
     (require 'package)
     (add-to-list 'package-archives
                  '("melpa" . "http://melpa.milkbox.net/packages/") t)
     (package-initialize)
   #+end_src

   Next, I'll define a function to check if a package is installed and
   install it if it isn't.

   #+begin_src emacs-lisp
     (defun require-package (package-name)
       "Install a package if it isn't installed"
       (unless (package-installed-p package-name)
               (package-install package-name)))

     (defun require-packages (package-names)
       "Install a list packages if they aren't installed"
       (dolist (package-name package-names)
         (require-package package-name)))
   #+end_src

* Personal Information

   This is just some of my personal information, which I'd like to
   have available.

   #+begin_src emacs-lisp
     (setq user-full-name "Michael Simpson")
     (setq user-mail-address "mjs2600@gmail.com")
   #+end_src

   This loads passwords into emacs if there's a password file.

   #+begin_src emacs-lisp
     (setq password-file "~/.passwords.gpg")
     (and (file-exists-p password-file)
          (load-file password-file))
   #+end_src

* Basic Configuration

   The purpose of this section is to make emacs a little more
   usable. I'll start by turning on =ido-mode=.

   #+begin_src emacs-lisp
     (ido-mode t)
   #+end_src

   The next step is to use =smex=, which does the same thing as ido
   mode, but for M-x.

   #+begin_src emacs-lisp
     (require-package 'smex)
     (smex-initialize)
     (global-set-key (kbd "M-x") 'smex)
   #+end_src

** ELisp

   The next thing I'll need to feel more at home is better ELisp
   support. I'll start by adding =smartparens=.

   #+begin_src emacs-lisp
     (require-package 'smartparens)
     (require 'smartparens-config)
     (smartparens-global-mode 1)
   #+end_src

   Now, let's make it easier to tell all of the parens apart with
   =rainbow-delimiters=.

   #+begin_src emacs-lisp
     (require-package 'rainbow-delimiters)
     (global-rainbow-delimiters-mode)
   #+end_src

* Style

   Let's my Emacs a little prettier. First thing I'll do pick a color
   scheme. =zenburn= looks nice enough for now.

   #+begin_src emacs-lisp
     (require-package 'zenburn-theme)
     (load-theme 'zenburn)
   #+end_src

   =pretty-mode= always makes things look a little nicer too.

   #+begin_src emacs-lisp
     (require-package 'pretty-mode)
     (global-pretty-mode)
   #+end_src

* eVIl

   First, I need to require all of the eVIl packages that I'll use.

   #+begin_src emacs-lisp
     (require-packages '(evil
                         evil-leader
                         evil-surround))
   #+end_src

   Next I need to turn on evil-mode.

   #+begin_src emacs-lisp
     (evil-mode t)
     (global-evil-leader-mode t)
     (global-evil-surround-mode t)
   #+end_src

   Now I'll setup my leader key to make it match my vim setup.

   #+begin_src emacs-lisp
     (evil-leader/set-leader "<SPC>")

     (evil-leader/set-key
       "b" 'ido-switch-buffer
       "f" 'ido-find-file
       "g" 'magit-status
       "k" 'ido-kill-buffer
       "m" 'eshell
       "s" 'ack
       "x" 'smex)
   #+end_src

   Disable evil in certain modes

   #+begin_src emacs-lisp
     (evil-set-initial-state 'magit-log-edit-mode 'emacs)
   #+end_src

** Elixir

   I need to setup some Elixir specific leader bindings.

   #+begin_src emacs-lisp
     (evil-leader/set-key-for-mode 'elixir-mode
       "t" 'elixir-mix-test)
   #+end_src

* YASnippets

   I'll need something to manage snippets.

   #+begin_src emacs-lisp
     (require-package 'yasnippet)
     (yas-global-mode 1)
   #+end_src

* Entertainment
** RSS

* Git

   I use git for everything so =magit= is a must. I also like using
   gitflow, but I've never used =magit-gitflow=. For now, I'm just
   trying it out. If I don't end up using it, I'll remove it soon.

   #+begin_src emacs-lisp
     (require-packages '(magit
                         magit-gitflow))

     (require 'magit-gitflow)
     (add-hook 'magit-mode-hook 'turn-on-magit-gitflow)
   #+end_src
* Markdown

  I need markdown support for notes

  #+begin_src emacs-lisp
    (require-package 'markdown-mode)
  #+end_src
* Keybindings

  #+begin_src emacs-lisp
    (global-set-key (kbd "C-x m") 'eshell)
    (global-set-key (kbd "C-c r") 'ielm)
    (global-set-key (kbd "C-c g") 'magit)

  #+end_src
* Social

  Add Twitter support

  #+begin_src emacs-lisp
    (require-package 'twittering-mode)
  #+end_src
